import { createClient } from "@supabase/supabase-js";

// Minimal client used until the autogenerated client/types are available
export const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL!,
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY!
);
